services:
  # Backend (Express + TS)
  - type: web
    name: fra-backend-express
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false   # set manually in Render dashboard

  # Dashboard (CRA build - Static Site)
  - type: web
    name: fra-dashboard
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false   # backend URL after deploy

  # Map (Vite + React - Static Site)
  - type: web
    name: fra-map
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false   # backend URL after deploy

  # Forest Alert (Express)
  - type: web
    name: forest-alert
    env: node
    buildCommand: npm install
    startCommand: npm start
