services:
  # Backend (Express + TypeScript)
  - type: web_service
    name: fra-backend
    env: node
    buildCommand: cd fra-backend-express-complete && npm install && npm run build
    startCommand: cd fra-backend-express-complete && npm start
    envVars:
      - key: DATABASE_URL
        sync: false   # set manually in Render dashboard
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080

  # Dashboard (React - CRA)
  - type: static_site
    name: fra-dashboard
    buildCommand: cd fra-dashboard && npm install && npm run build
    publishPath: fra-dashboard/build

  # Map (React - Vite)
  - type: static_site
    name: fra-map
    buildCommand: cd TINA/fra-map && npm install && npm run build
    publishPath: TINA/fra-map/dist

  # Forest Alert (Express backend)
  - type: web_service
    name: forest-alert
    env: node
    buildCommand: cd forest-alert && npm install
    startCommand: cd forest-alert && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
