apiVersion: 1
services:
  - type: web
    name: fra-backend
    rootDir: fra-backend-express-complete
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

  - type: static
    name: fra-dashboard
    rootDir: fra-dashboard
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false

  - type: static
    name: fra-map
    rootDir: TINA/fra-map
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false

  - type: static
    name: forest-alert
    rootDir: forest-alert
    staticPublishPath: .
