apiVersion: 1
services:
  # Backend (Express + TypeScript)
  - type: web
    name: fra-backend
    rootDir: fra-backend-express-complete
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false  # set in Render dashboard
      - key: NODE_ENV
        value: production

  # Dashboard (React - CRA)
  - type: static
    name: fra-dashboard
    rootDir: fra-dashboard
    buildCommand: npm ci && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false  # set to https://fra-backend.onrender.com (or your backend URL)

  # Map (React - Vite)
  - type: static
    name: fra-map
    rootDir: TINA/fra-map
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false  # set to your backend URL

  # Forest Alert (static site)
  - type: static
    name: forest-alert
    rootDir: forest-alert
    publishPath: .
