apiVersion: 1
services:
  - type: web
    name: fra-backend
    rootDir: fra-backend-express-complete
    env: docker
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production

  - type: web
    name: fra-dashboard
    rootDir: fra-dashboard
    env: static
    buildCommand: npm ci && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false

  - type: web
    name: fra-map
    rootDir: TINA/fra-map
    env: static
    buildCommand: npm ci && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false

  - type: web
    name: forest-alert
    rootDir: forest-alert
    env: static
    publishPath: .
