services:
  # Backend (Express + TS)
  - type: web
    name: fra-backend-express
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false   # you’ll set it manually in Render dashboard

  # Dashboard (Create React App)
  - type: static
    name: fra-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false   # set this to backend URL after deploy

  # Map (Vite + React)
  - type: static
    name: fra-map
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false   # set this to backend URL after deploy

  # Forest Alert (simple Express app)
  - type: web
    name: forest-alert
    env: node
    buildCommand: npm install
    startCommand: npm start
